### ISSUE TITLE
Rework demos/examples in light of #169

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#194]
Look at https://github.com/ksonnet/ksonnet/pull/169.

We can now omit the `--name` param from most of our examples and demos.  We should do a quick scrub to simplify based on that.

**Comment by abiogenesis-now** [comment]
on my radar! I'm offline for a few hours this afternoon but i'll fix when I get back (also will incorporate doc changes for https://github.com/ksonnet/ksonnet/pull/201)

**Comment by abiogenesis-now** [comment]
There are a couple of changes that need to merge for this---e.g. PRs for `ksonnet`, `ksonnet-playground`, and `ksonnet-next-site`. I can make these.

(However, I'm slightly concerned that this makes the stuff in our prototypes registry (`parts`) look a bit sparse, since many of them don't have parameters other than `--name` and `--namespace`. Need to investigate this afterwards).

**Comment by abiogenesis-now** [comment]
basically just need to make sure the playground redeploys and we'll be good. i'm pretty sure i can remember that, so closing this issue now
