### ISSUE TITLE
Should be able to be used offline

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#204]
I'm on a plane with minikube and `ks init` fails.

```console
$ ks init foo
INFO  Using context 'minikube' from the kubeconfig file specified at the environment variable $KUBECONFIG
INFO  Creating a new app 'foo' at path '/Users/jbeda/tmp/foo'
ERROR Get https://api.github.com/repos/ksonnet/parts/commits/master: dial tcp: lookup api.github.com: no such host
```

**Comment by abiogenesis-now** [comment]
ok, this is caused by the `incubator` registry, which we set up by default (https://github.com/ksonnet/ksonnet/blob/2b05b5b9ad7f58e24c64d2134bebf634faefaa95/metadata/interface.go#L102)

@jessicayuen not sure what the behavior fix should be---some ideas:
* `ks init` should attempt to set up registry, but skip if there is no network connection (so that app directory is still created).
* if any `ks pkg` or `ks registry` command is called and there is no pre-existing `incubator` info in `.ksonnet` or `app.yaml`, we attempt to download it? and if there is no network, we display a suitable error message.

^ actually, maybe we don't even need the first part if the second part is implemented? 
(just offering ideas because i happen to be online now)

**Comment by jbeda** [comment]
Probably not a p0, but wanted to note it.

Delay loading the incubator stuff might be a good idea.  We should think though about when/how we download/update that stuff.  What happens when we add a new pkg to that repo?

**Comment by abiogenesis-now** [comment]
^ that's a really good point cc @hausdorff (not for release, but just fyi for future)

**Comment by hausdorff** [comment]
I agree we should deal with this, and I agree that it's easy to lazily initialize registries.

The other obstacle to making `init` available offline is that we need to fetch the `swagger.json` from somewhere (by default from the relevant k8s release), and use that to generate the `k8s.libsonnet`. This issue is a bit more nuanced, and I think it's worth considering the options:

* We could simply not create the first environment if we can't get to the default place where `swagger.json` exists (although we'd presumably error out if the user manually provides a `swagger.json` that simply doesn't exist). We might also decide the same thing if we can't find the default `$KUBECONFIG`, and so on.
* We could cache a default `swagger.json`, and use that to generate the first environment.
* We could lazily initialize environments.

I mention the first two for completeness but I actually think that the third is the right answer, because we have to solve it anyway -- it is pretty much the same logic that's required when a user clones the project and wants to run `apply` (or something). Specifically: people aren't going to be checking in `k8s.libsonnet`, so this implies a `ks` equivalent of `npm install`, which would generate those files on behalf of the user. It is clear, I hope, that these are basically the same idea -- we have to get and cache a `swagger.json` lazily, when they have an internet connection.

So my proposed actions are:

1. Make registries lazily-initialized.
1. Make environments lazily-initialized.
1. [Unrelated to this issue] Hook up `ks install` (or whatever) to use these routines.

Thoughts?

**Comment by abiogenesis-now** [comment]
^ Lazily loading external dependencies and using a `ks install` for a freshly cloned repository make sense to me.

**Comment by redbaron** [comment]
Regarding swagger.json , there are 2 more options:
   - rely on swagger.json being provided by user using `--api-spec=file:swagger.json`
   - bundle swagger.json inside ks binary for last X kubernetes versions. `gzip -9` compressed that file is just 127 KB, not a big deal for 37MB binary.

**Comment by bryanl** [comment]
Going to add an option that will allow you to skip adding the default registry. This will allow you to init a ksonnet app without internet access. I'm thinking there should also be a way to add registries at I it time as well. Either GitHub or filesystem based.

**Comment by davidstack** [comment]
i use this command
  ks init test123 --api-spec=file:swagger.json
it still try to connect the internet to download ksonnet-lib

**Comment by runzhliu** [comment]
Try this one after download k8s swagger.json the version you wanted.

```
ks init <ks_app> --api-spec=file:/tmp/swagger.json --skip-default-registries
```
