### ISSUE TITLE
`prototype use -h` should output help docs 

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#21]
`prototype use -h` should output help docs when a single argument `--help` or `-h` is provided.

Currently receives the error:
```
➜  foobar git:(master) ✗ ../ks prototype use -h
ERROR No prototype names matched '-h'
```

Expect the same behavior outside of a ksonnet project dir, however currently receives:
```
➜  ksonnet git:(master) ✗ ./ks prototype use -h 
ERROR 'prototype use' can only be run in a ksonnet application directory:

No ksonnet application found
```

**Comment by hausdorff** [comment]
The `--help` command was disabled specifically so that we didn't accidentally bork templates with that expose a variable called `--help`.

I think you're right to identify this as unintuitive behavior, though, so what I propose is: if there is exactly one command argument, and it is `--help`, we print the help message.
