### ISSUE TITLE
github rate limited me; support auth?

### ISSUE THREAD

**Issue by jlewi** [ksonnet/ksonnet#233]
I ran into rate limiting while testing out registry support (#228). The error I got was

```
ERROR GET https://api.github.com/repos/jlewi/kubeflow/commits/ksonnet_crd: 403 API rate limit exceeded for 108.222.64.88. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 26m06s]
```

**Comment by hausdorff** [comment]
@jlewi Did you get `ks` from `brew`, or are you running a recent build of `ks`? If so then [this pr](https://github.com/ksonnet/ksonnet/pull/201) adds support for the `GITHUB_TOKEN` environment variable, so that you can do something like:

```
$ GITHUB_TOKEN=foo ks whatever
```

I do think we should take an issue here, though:

- [ ] When a user gets rate limited, output an error message that tells them to use `GITHUB_TOKEN`.

**Comment by jlewi** [comment]
I was building from source so the environment variable would solve my problem.

**Comment by CodingMrWang** [comment]
Error: API rate limit exceeded for  XXX, (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.). I got this for gitalk, do you know why

**Comment by shomron** [comment]
@CodingMrWang I'm not sure I understood - if the error was from `gitalk`, perhaps you should post an issue for that project?
