### ISSUE TITLE
Badly formatted client-go version string

### ISSUE THREAD

**Issue by lblackstone** [ksonnet/ksonnet#250]
Running `ks version` produces the following:
```
...
client-go version: v1.6.8-beta.0+$Format:%h$
```

Probably related to https://github.com/kubernetes/kubernetes/issues/52782

**Comment by bryanl** [comment]
Dependencies are versioned, so when building client-go, we don't get the tags from the repository. We'll have to address this another way.

**Comment by hausdorff** [comment]
See: https://github.com/ksonnet/kubecfg/issues/92

**Comment by hausdorff** [comment]
@bryanl, @jessicayuen The options as I see them are:

* Remove the suffix that contains the format string. That information should be recoverable from the `ks` version anyway, since the dependency is vendored.
* Somehow communicate the SHA from build to this code, and set the commit SHA appropriately.
* File a bug against upstream and fix ourselves.

Of these I think the first is most reasonable, since I see this as an annoying but not high-ROI issue.

**Comment by hausdorff** [comment]
@bryanl ok, so you are saying you agree we should go with option (1)?

**Comment by bryanl** [comment]
@hausdorff I was offering up a fourth idea by combining `apimachineryversion.Info.Major` and apimachineryversion.Info.Minor`.

**Comment by jessicayuen** [comment]
@bryanl fixed this issue in #285
