### ISSUE TITLE
Unable to install packages with the same name under different registries

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#269]
Related to #262: if I have a package 'redis' in both registries, an error will occur when trying to install redis from the second registry (if redis is already installed from the first registry)

```
➜  testdir git:(prototype-reg-name) ✗ ks registry add incubatorXYZ github.com/ksonnet/parts/tree/master/incubator
➜  testdir git:(prototype-reg-name) ✗ ks registry list
NAME         PROTOCOL URI
====         ======== ===
incubatorXYZ github   github.com/ksonnet/parts/tree/master/incubator
incubator    github   github.com/ksonnet/parts/tree/master/incubator    
➜  testdir git:(prototype-reg-name) ✗ ks pkg install incubator/redis    
INFO  Retrieved 8 files
➜  testdir git:(prototype-reg-name) ✗ ks pkg install incubatorXYZ/redis
ERROR Library 'redis' already exists
```

 This shouldn't happen since the `vendor/` directory structure is categorized by registry.

**Comment by hausdorff** [comment]
@jessicayuen This is the designed behavior. Can you share the rationale for why we consider this a bug?

**Comment by hausdorff** [comment]
@jessicayuen Also, in case it's useful, our rationale for why this _isn't_ a bug was:

1. It's not clear how to make code work when two libraries have two different names. How does something like `import "redis/redis.libsonnet"` work? If we include the registry name (_e.g._, `import "incubator/redis/redis"`, what happens when we rename the registry? (This is very related to #263 and #68.)
1. If you want two libraries that are called the same thing in different registries, the preferred way to deal with this is to give them different names, _e.g._, `incubator/redis` -> `redis` and `your-team/redis` -> `redis-v2` or something.

**Comment by hausdorff** [comment]
@jessicayuen and I had an offline conversation about this. At this point we agree that:

* This is designed behavior. We explicitly chose to follow the convention set by other languages (_e.g._, NPM for JavaScript, Maven for Java, NuGet for C#) and force each package to have a completely unique name that does _not_ refer to the private/public/local NPM/Maven/NuGet registry the package was obtained from.
* This is an important enough design point in the design of the package management system that we think we should make a design doc if we want to change this behavior now.

As for steps forward, we agree:

* We will not be writing a design doc or pursuing changing this behavior at this time.
* We will fix the error message to be more clear. (_i.e._, we need to tell the user to name the package something else if they want to `pkg install`.)
