### ISSUE TITLE
ERROR user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by tomwilkie** [ksonnet/ksonnet#298]
/kind bug

**What happened**:

Downloaded https://github.com/ksonnet/ksonnet/releases/download/v0.8.0/ks_0.8.0_linux_amd64.tar.gz and tried to use it in CircleCI (ie Linux) - got the error "ERROR user: Current not implemented on linux/amd64".  

Seems to be https://github.com/golang/go/issues/14626, which was fixed ages ago - what version of go was used to compile the release?

**How to reproduce it (as minimally and precisely as possible)**:

Download https://github.com/ksonnet/ksonnet/releases/download/v0.8.0/ks_0.8.0_linux_amd64.tar.gz and run `ks diff <env>`

**Environment**:
- ksonnet version (use `ks version`):
```
# ks version
ksonnet version: 0.8.0
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$
```
- Kubernetes version (use `kubectl version`):

**Comment by tomwilkie** [comment]
I tried cross-compilling with go1.9.2 and I still get the error

**Comment by tomwilkie** [comment]
It seems a workaround is specify USER in the env.

**Comment by bryanl** [comment]
I pulled the binary down to a ubuntu 16.04 box and it runs fine. It doesn't run in Alpine, looks like the binary wasn't compiled with `CGO_ENABLED=0`.  We'll have to get that updated and new linux binaries released.

**Comment by tomwilkie** [comment]
Weird, I could reproduce locally with a docker image based on ubuntu:xenial-20170517.1.  Did you box have a `USER` env define?

**Comment by bryanl** [comment]
For the time being, if you can add a `USER` env var as a work around, that should allow you to progress. I believe this issue stems from cross compiling for linux on a mac. If we compile with `CGO_ENABLED=0`, the binary can't ask glibc for the current user information, so it heads to the environment. If you don't have a user set, it bails out. If we compile with `CGO_ENABLED=1` on a mac, this won't work either because it won't be able to link in glibc. The solution here is to do our builds on the target, or to do `CGO_ENABLED=0` and require a `USER` env to be set.

**Comment by jessesuen** [comment]
This still seems to be an issue in v0.10.0-alpha.2. We are working around it by setting `env USER root` but wanted to let you know.
