### ISSUE TITLE
ks import -f some-component.yaml does not set component index in components/params.libsonnet

### ISSUE THREAD

**Issue by jessesuen** [ksonnet/ksonnet#437]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT
/kind bug

**What happened**:

After importing a yaml using `ks import`, the params.libsonnet is missing the -X index.
```
$ ks import -f ~/tmp/kube-ops-view-deploy.yaml
INFO Writing component at '/Users/jsuen/ws/myapps/kube-ops-view/components/kube-ops-view-deploy.yaml'

$ cat components/params.libsonnet
{
  global: {
  },
  components: {
    // Component-level parameters, defined initially from 'ks prototype use ...'
    // Each object below should correspond to a component in the components/ directory
    "kube-ops-view-deploy": {

    },
  },
}
```

**What you expected to happen**:

According to chat with @bryanl, the component name in params.libsonnet should be: "kube-ops-view-deploy-0" instead of "kube-ops-view-deploy"

**How to reproduce it (as minimally and precisely as possible)**: See above

**Environment**:
- ksonnet version (use `ks version`):

```
$ ks version
ksonnet version: 0.10.0-alpha.1
jsonnet version: v0.10.0
client-go version: 1.8
```

**Comment by jessesuen** [comment]
I have some questions and concerns about this behavior. `ks import -f` accepts json or yaml files. If the file is json, there would only ever be one component, since valid JSON does not contain multiple objects in a single .json file. On the other hand, YAML supports multiple objects with the `---` separator, which forces ksonnet to index the component with a -N suffix. 

Given the difference between .json vs. .yaml files, it seems to me that there would be a discrepancy in behavior when importing .json files vs. .yaml files. In the case of json, it seems like it wouldn't make sense to have an -0 suffix. But in the case of yaml, it would need to have -0, -1.

Having suffixes presents it's own set of issues, because since ordering of the objects within the yaml file suddenly becomes important, and parameters are now sensitive to what order they appear in the yaml file.

I'm wondering to have consistent, simpler behavior, could ksonnet simply require that drop-in .yaml and .json be a single object per file? If this is enforced, component name would simply be the filename (minus extension), and we would not have to deal with -X suffixes on components.

I feel like this tradeoff for simplicity, would be preferable over the benefit from allowing multiple objects defined in a single .yaml file.

**Comment by bryanl** [comment]
This is a difficult place. There needs to be some set of nomenclature to identify the different objects in a file. The reason There is support for multiple is because many projects share their objects as a single file. The goals is to allow `ks import -f https://url` to work. 

The ordering should be important. It's an array, if you change the value, you change the component. If you delete a value, it will change the component. I don't think this will be touched before 0.10 drops, but I was thinking that it would be possible to specify objects by their kind/name. This would ultimately allow us to drop the index and remove some of the confusion.
