### ISSUE TITLE
Image resolver was removed

### ISSUE THREAD

**Issue by burdiyan** [ksonnet/ksonnet#569]
/kind feature

**What happened**:

There used to be a flag that you could specify to resolve image tags to digests. Similar to the one existing in `kubecfg`. But after this commit: https://github.com/ksonnet/ksonnet/commit/a24017ec5ecbdf49099442bb25e18294de7f204d#diff-78d256502ca14be2d328aebb8900be61 it was removed. I wonder what was the reason, and whether there's currently a way to resolve image digests.

```
$ ks version

ksonnet version: 0.10.2
jsonnet version: v0.10.0
client-go version: 1.8
```

**Comment by bryanl** [comment]
Yes, it was removed. There were no tests coverage and it appeared to be an used artifact from embedding kubecfg. It can be re-added.

**Comment by burdiyan** [comment]
I think It has a lot of value to be honest. It existence was the thing that made me moving from Helm to Ksonnet. Basically I want to keep all manifest in one place, but deploy when my source code is pushed. And on deploy I only need to change image tag (digest to be correct) without needing to go the manifests repo and update the parameter. Manifests would always resolve to the digest of a given "stable" tag.

Let me know if it's not clear.

**Comment by bryanl** [comment]
This is good example. We'll get this on the backlog to get it back into ksonnet.

**Comment by bryanl** [comment]
I've reviewed this, and we are going to take the following approach:

`ks param set` will have a new argument, `--resolve-image`, that will attempt to resolve the image to its digest. ksonnet will not automatically resolve image tags because that means the configuration can vary due to external changes not caused by a direct action in ksonnet. We're aiming for repeatable applies, and variable image digests defeats this.

**Comment by burdiyan** [comment]
@bryanl that makes sense. For those who want to resolve tag in a more “at runtime” fashion could still do that.
