### ISSUE TITLE
X.509 certificate isuue when executing ks init

### ISSUE THREAD

**Issue by bobhenkel** [ksonnet/ksonnet#838]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**What happened**:
See closed issue https://github.com/ksonnet/ksonnet/issues/436
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`): 0.12.0
- Kubernetes version (use `kubectl version`): 1.10.3

**Comment by shomron** [comment]
@bobhenkel this issue was resolved in #832 and is available if you build master. Once you have done that, you can pass the new `—tls-skip-verify` flag to avoid the certificate errors stemming from the proxy.

I’ll close this issue for now, please let me know if the above solves your problem.

**Comment by shomron** [comment]
Glad to hear it!

I see two primary paths forward:

* Allow specifying the trusted certificate chain - this is prudent and will provide verified communications, however there would be some burden on the user to understand their proxy configuration and assemble the necessary certificates
* Reduce external network requests for certain use-cases - we could consider prepackaging Kubernetes API specs rather than fetching them - however this could increase our distribution size significantly, as well as being an always-moving target. GitHub/Helm registries would still need internet access.

In the meantime, I'm glad to hear that you're unblocked!
